stages:
  - image

variables:
  BUILD:
    value: debug_tools
    description: "Path to folder contains Dockerfile"
  TAG:
    value: ""
    description: "Build tag"

build custom image:
  stage: image
  image: docker:26.1.4
  rules:
    - if: $BUILD && $TAG
      variables:
        DOCKERFILE: dockerfiles/$BUILD/Dockerfile
        IMAGE: $DOCKERHUB_USERNAME/$BUILD:$TAG
        DOCKER_CONTEXT: dockerfiles/$BUILD
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
  script:
    - echo $IMAGE
    - docker build -f $DOCKERFILE --network=host --build-arg TAG=$TAG -t $IMAGE $DOCKER_CONTEXT 
    - docker push $IMAGE
    - docker rmi $IMAGE
