version: "3.9"

x-var:
  resources:
    &resources
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1536M
        reservations:
          cpus: '0.15'
          memory: 256M
    restart: unless-stopped
    networks:
      - pi_services
  dashboard:
    &dashboard
    image: pawelmalak/flame:2.3.1
    environment:
      PASSWORD: "admin"
  uptime-kuma:
    &uptime-kuma
    image: louislam/uptime-kuma:1.23.2
  grafana:
    &grafana
    image: grafana/grafana-oss:10.0.8
  victoriametrics:
    &victoriametrics
    image: victoriametrics/victoria-metrics:v1.93.5
  mongo:
    &mongo
    image: mongo:5.0.21
  elasticsearch:
    &elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
  elasticsearch_exporter:
    &elasticsearch_exporter
    image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.6.0
  graylog:
    &graylog
    image: graylog/graylog:5.1.5
  node_exporter:
    &node_exporter
    image: prom/node-exporter:v1.6.1
  black_box_exporter:
    &black_box_exporter
    image: prom/blackbox-exporter:v0.24.0
  snmp_exporter:
    &snmp_exporter
    image: prom/snmp-exporter:v0.22.0
  cadvisor:
    &cadvisor
    image: gcr.io/cadvisor/cadvisor-amd64:v0.47.2
  minio:
    &minio
    image: minio/minio:RELEASE.2023-08-16T20-17-30Z
  traefik:
    &traefik
    image: traefik:v2.10.4
  gitlab_runner:
    &gitlab_runner
    image: gitlab/gitlab-runner:v16.4.0
  samba:
    &samba
    image: glowcow/samba:4.17.10
  transmission:
    &transmission
    image: glowcow/transmission:3.00

services:
  dashboard:
    <<:
      - *dashboard
      - *resources
    container_name: pi_dashboard_dc
    volumes:
      - /docker_apps/flame:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.rule=Host(`pi.glowcow.xyz`)"
      - "traefik.http.routers.dashboard.middlewares=https-redirect"
      - "traefik.http.routers.dashboard-secure.entrypoints=websecure"
      - "traefik.http.routers.dashboard-secure.rule=Host(`pi.glowcow.xyz`)"
      - "traefik.http.routers.dashboard-secure.tls=true"
      - "traefik.http.routers.dashboard-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.dashboard-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.dashboard-secure.tls.domains[0].sans=*.pi.glowcow.xyz"
  uptime-kuma:
    <<:
      - *uptime-kuma
      - *resources
    container_name: kuma_dc
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /docker_apps/kuma:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.entrypoints=web"
      - "traefik.http.routers.kuma.rule=Host(`kuma.pi.glowcow.xyz`)"
      - "traefik.http.routers.kuma.middlewares=https-redirect"
      - "traefik.http.routers.kuma-secure.entrypoints=websecure"
      - "traefik.http.routers.kuma-secure.rule=Host(`kuma.pi.glowcow.xyz`)"
      - "traefik.http.routers.kuma-secure.tls=true"
      - "traefik.http.routers.kuma-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.kuma-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.kuma-secure.tls.domains[0].sans=*.pi.glowcow.xyz"
  grafana:
    <<:
      - *grafana
      - *resources
    container_name: grafana_dc
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=victoriametrics-datasource
    depends_on:
      - victoriametrics
      - elasticsearch
    volumes:
      - /docker_apps/grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=Host(`grafana.pi.glowcow.xyz`)"
      - "traefik.http.routers.grafana.middlewares=https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.pi.glowcow.xyz`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.grafana-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.grafana-secure.tls.domains[0].sans=*.pi.glowcow.xyz"
  victoriametrics:
    container_name: victoriametrics_dc
    <<:
      - *victoriametrics
      - *resources
    volumes:
      - /docker_apps/victoriametrics/data:/storage
      - /docker_apps/victoriametrics/scrape.yaml:/etc/vm/scrape.yaml
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "--retentionPeriod=6"
      - "--promscrape.config=/etc/vm/scrape.yaml"
      - "--promscrape.maxScrapeSize=50MB"
      - "--maxLabelsPerTimeseries=80"
    depends_on:
      - elasticsearch_exporter
      - black_box_exporter
      - snmp_exporter
      - node_exporter
      - cadvisor
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.victoriametrics.entrypoints=web"
      - "traefik.http.routers.victoriametrics.rule=Host(`vm.pi.glowcow.xyz`)"
      - "traefik.http.routers.victoriametrics.middlewares=https-redirect"
      - "traefik.http.routers.victoriametrics-secure.entrypoints=websecure"
      - "traefik.http.routers.victoriametrics-secure.rule=Host(`vm.pi.glowcow.xyz`)"
      - "traefik.http.routers.victoriametrics-secure.tls=true"
      - "traefik.http.routers.victoriametrics-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.victoriametrics-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.victoriametrics-secure.tls.domains[0].sans=*.pi.glowcow.xyz"
  mongo:
    <<:
      - *mongo
      - *resources
    container_name: mongo_dc
    volumes:
      - /docker_apps/mongo:/data/db
  elasticsearch:
    <<:
      - *elasticsearch
      - *resources
    container_name: elasticsearch_dc
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    volumes:
      - /docker_apps/es:/usr/share/elasticsearch/data
  elasticsearch_exporter:
    <<:
      - *elasticsearch_exporter
      - *resources
    container_name: elasticsearch_exporter_dc
    command:
     - '--es.uri=http://elasticsearch:9200'
  graylog:
    <<:
      - *graylog
      - *resources
    container_name: graylog_dc
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - /docker_apps/graylog/data:/usr/share/graylog/data
      - /docker_apps/graylog/config:/usr/share/graylog/data/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.graylog.loadbalancer.server.port=9000"
      - "traefik.http.routers.graylog.entrypoints=web"
      - "traefik.http.routers.graylog.rule=Host(`graylog.pi.glowcow.xyz`)"
      - "traefik.http.routers.graylog.middlewares=https-redirect"
      - "traefik.http.routers.graylog-secure.entrypoints=websecure"
      - "traefik.http.routers.graylog-secure.rule=Host(`graylog.pi.glowcow.xyz`)"
      - "traefik.http.routers.graylog-secure.tls=true"
      - "traefik.http.routers.graylog-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.graylog-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.graylog-secure.tls.domains[0].sans=*.pi.glowcow.xyz"
      - "traefik.tcp.routers.graylog-tcp-1.entrypoints=graylog-tcp-1"
      - "traefik.tcp.routers.graylog-tcp-1.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.graylog-tcp-1.service=graylog-tcp-1"
      - "traefik.tcp.services.graylog-tcp-1.loadbalancer.server.port=1514"
      - "traefik.udp.routers.graylog-udp-1.entrypoints=graylog-udp-1"
      - "traefik.udp.routers.graylog-udp-1.service=graylog-udp-1"
      - "traefik.udp.services.graylog-udp-1.loadbalancer.server.port=1514"
      - "traefik.udp.routers.graylog-udp-2.entrypoints=graylog-udp-2"
      - "traefik.udp.routers.graylog-udp-2.service=graylog-udp-2"
      - "traefik.udp.services.graylog-udp-2.loadbalancer.server.port=12201"
  black_box_exporter:
    <<:
      - *black_box_exporter
      - *resources
    container_name: black_box_exporter_dc
    volumes:
      - /docker_apps/bbexporter:/config/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bbox.entrypoints=web"
      - "traefik.http.routers.bbox.rule=Host(`bbexporter.pi.glowcow.xyz`)"
      - "traefik.http.routers.bbox.middlewares=https-redirect"
      - "traefik.http.routers.bbox-secure.entrypoints=websecure"
      - "traefik.http.routers.bbox-secure.rule=Host(`bbexporter.pi.glowcow.xyz`)"
      - "traefik.http.routers.bbox-secure.tls=true"
      - "traefik.http.routers.bbox-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.bbox-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.bbox-secure.tls.domains[0].sans=*.pi.glowcow.xyz"
  node_exporter:
    <<:
      - *node_exporter
      - *resources
    container_name: node_exporter_dc
    volumes:
      - /:/hostfs:ro,rslave
    command:
      - '--path.rootfs=/hostfs'
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nex.entrypoints=web"
      - "traefik.http.routers.nex.rule=Host(`nex01.pi.glowcow.xyz`)"
      - "traefik.http.routers.nex.middlewares=https-redirect"
      - "traefik.http.routers.nex-secure.entrypoints=websecure"
      - "traefik.http.routers.nex-secure.rule=Host(`nex01.pi.glowcow.xyz`)"
      - "traefik.http.routers.nex-secure.tls=true"
      - "traefik.http.routers.nex-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.nex-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.nex-secure.tls.domains[0].sans=*.pi.glowcow.xyz"
  snmp_exporter:
    <<:
      - *snmp_exporter
      - *resources
    container_name: snmp_exporter_dc
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"
    volumes:
      - /docker_apps/snmp_exporter/snmp.yml:/etc/snmp_exporter/snmp.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snmp.entrypoints=web"
      - "traefik.http.routers.snmp.rule=Host(`snmp.pi.glowcow.xyz`)"
      - "traefik.http.routers.snmp.middlewares=https-redirect"
      - "traefik.http.routers.snmp-secure.entrypoints=websecure"
      - "traefik.http.routers.snmp-secure.rule=Host(`snmp.pi.glowcow.xyz`)"
      - "traefik.http.routers.snmp-secure.tls=true"
      - "traefik.http.routers.snmp-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.snmp-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.snmp-secure.tls.domains[0].sans=*.pi.glowcow.xyz"
  cadvisor:
    <<:
      - *cadvisor
      - *resources
    container_name: cadvisor_dc
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  minio:
    <<:
      - *minio
      - *resources
    container_name: minio_dc
    volumes:
      - /docker_apps/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --address :9000 --console-address :9001
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.routers.minio.entrypoints=web"
      - "traefik.http.routers.minio.rule=Host(`minio.pi.glowcow.xyz`)"
      - "traefik.http.routers.minio.middlewares=https-redirect"
      - "traefik.http.routers.minio-secure.service=minio"
      - "traefik.http.routers.minio-secure.entrypoints=websecure"
      - "traefik.http.routers.minio-secure.rule=Host(`minio.pi.glowcow.xyz`)"
      - "traefik.http.routers.minio-secure.tls=true"
      - "traefik.http.routers.minio-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.minio-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.minio-secure.tls.domains[0].sans=*.pi.glowcow.xyz"
      - "traefik.http.services.s3.loadbalancer.server.port=9000"
      - "traefik.http.routers.s3.service=s3"
      - "traefik.http.routers.s3.entrypoints=web"
      - "traefik.http.routers.s3.rule=Host(`s3.pi.glowcow.xyz`)"
      - "traefik.http.routers.s3.middlewares=https-redirect"
      - "traefik.http.routers.s3-secure.service=s3"
      - "traefik.http.routers.s3-secure.entrypoints=websecure"
      - "traefik.http.routers.s3-secure.rule=Host(`s3.pi.glowcow.xyz`)"
      - "traefik.http.routers.s3-secure.tls=true"
      - "traefik.http.routers.s3-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.s3-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.s3-secure.tls.domains[0].sans=*.pi.glowcow.xyz"
  traefik:
    <<:
      - *traefik
      - *resources
    container_name: traefik_dc
    env_file:
      - .godaddy.env
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--accesslog=false"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/dev/stdout"
      - "--entrypoints.traefik.address=:8888"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.graylog-tcp-1.address=:1514"
      - "--entrypoints.graylog-udp-1.address=:1514/udp"
      - "--entrypoints.graylog-udp-2.address=:12201/udp"
      - "--entrypoints.smb-tcp-1.address=:445"
      - "--entrypoints.smb-tcp-2.address=:139"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--serversTransport.insecureSkipVerify=true"
      - "--metrics.prometheus=true"
      # ACME V2 supports wildcard certificates.
      # Wildcard certificates can only be generated through a DNS-01 challenge.
      - "--certificatesresolvers.wildcard-godaddy.acme.tlschallenge=false"
      - "--certificatesResolvers.wildcard-godaddy.acme.dnsChallenge.provider=godaddy"
      - "--certificatesResolvers.wildcard-godaddy.acme.dnsChallenge.delayBeforeCheck=0"
      # Email address used for registration.
      - "--certificatesresolvers.wildcard-godaddy.acme.email=glowcow@gmail.com"
      # Certificates storage
      - "--certificatesresolvers.wildcard-godaddy.acme.storage=/tls-certificates/acme.json"
    ports:
      - 80:80
      - 443:443
      - 8888:8888
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201/udp
      - 139:139
      - 445:445
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/docker_apps/traefik/certs:/tls-certificates"
      - "/docker_apps/traefik/dynamic.yml:/etc/traefik/dynamic.yml"
    depends_on:
      - dashboard
      - graylog
      - samba
      - grafana
      - node_exporter
      - black_box_exporter
      - snmp_exporter
      - uptime-kuma
      - transmission
      - victoriametrics
      - minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`tf.pi.glowcow.xyz`)"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`tf.pi.glowcow.xyz`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.pi.glowcow.xyz"
      - "traefik.http.routers.traefik-secure.service=api@internal"
  gitlab_runner:
    <<:
      - *gitlab_runner
      - *resources
    container_name: gitlab_runner_dc
    depends_on:
      - minio
    volumes:
      - /docker_apps/gitlab_runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  samba:
    <<:
      - *samba
      - *resources
    container_name: samba_dc
    volumes:
      - /docker_apps/samba/private/:/var/lib/samba/private/
      - /docker_apps/samba/config/:/etc/samba/
      - /NAS/:/NAS/
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.smb-tcp-1.entrypoints=smb-tcp-1"
      - "traefik.tcp.routers.smb-tcp-1.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smb-tcp-1.service=smb-tcp-1"
      - "traefik.tcp.services.smb-tcp-1.loadbalancer.server.port=445"
      - "traefik.tcp.routers.smb-tcp-2.entrypoints=smb-tcp-2"
      - "traefik.tcp.routers.smb-tcp-2.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smb-tcp-2.service=smb-tcp-2"
      - "traefik.tcp.services.smb-tcp-2.loadbalancer.server.port=139"
  transmission:
    <<:
      - *transmission
      - *resources
    container_name: transmission_dc
    volumes:
      - /docker_apps/transmission/:/etc/transmission-daemon/
      - /NAS/Downloads/:/Downloads/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tm.entrypoints=web"
      - "traefik.http.routers.tm.rule=Host(`tm.pi.glowcow.xyz`)"
      - "traefik.http.routers.tm.middlewares=https-redirect"
      - "traefik.http.routers.tm-secure.entrypoints=websecure"
      - "traefik.http.routers.tm-secure.rule=Host(`tm.pi.glowcow.xyz`)"
      - "traefik.http.routers.tm-secure.tls=true"
      - "traefik.http.routers.tm-secure.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.tm-secure.tls.domains[0].main=pi.glowcow.xyz"
      - "traefik.http.routers.tm-secure.tls.domains[0].sans=*.pi.glowcow.xyz"

networks:
  pi_services:
    name: pi_services
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/122
